# yaml-language-server: $schema=https://raw.githubusercontent.com/suzuki-shunsuke/pinact/main/json-schema/pinact.json
version: 3

files:
  - pattern: ".github/workflows/*.yml"
  - pattern: ".github/actions/*/action.yml"

ignore_actions:
  - name: voicevox/merge-gatekeeper
    ref: main
  - name: cargo-bins/cargo-binstall
    ref: main
  - name: pypa/gh-action-pypi-publish
    ref: release/v1
