# yaml-language-server: $schema=./config.schema.yml

randomSeed: 0

source:
  providers:
    - cmudict
    - allShortWords
  maxNumWords: "all"

inference:
  provider: dummy
  concurrency: 10
  batch:
    type: fixed
    batchSize: 900
  rateLimit:
    maxRetries: 10
    waitMs: 60000
    throttleMs: 10
  gemini:
    apiKey: ""
    modelName: "gemini-2.0-flash"
  openai:
    apiBaseUrl: "https://api.openai.com/v1"
    apiKey: ""
    modelName: "text-davinci-003"
