# pnpm run tools:generateConfigSchema で生成。手動で編集しないでください。
type: object
properties:
  randomSeed:
    type: number
  source:
    type: object
    properties:
      providers:
        type: array
        items:
          type: string
          enum:
            - cmudict
            - allShortWords
      maxNumWords:
        anyOf:
          - type: number
          - type: string
            const: all
    required:
      - providers
      - maxNumWords
    additionalProperties: false
  inference:
    type: object
    properties:
      provider:
        type: string
        enum:
          - gemini
          - openai
          - dummy
      concurrency:
        type: number
      rateLimit:
        type: object
        properties:
          waitMs:
            type: number
          maxRetries:
            type: number
          throttleMs:
            type: number
        required:
          - waitMs
          - maxRetries
          - throttleMs
        additionalProperties: false
      batch:
        anyOf:
          - type: object
            properties:
              type:
                type: string
                const: fixed
              batchSize:
                type: number
            required:
              - type
              - batchSize
            additionalProperties: false
          - type: object
            properties:
              type:
                type: string
                const: bisect
              maxBatchSize:
                type: number
              ratio:
                type: number
            required:
              - type
              - maxBatchSize
              - ratio
            additionalProperties: false
      gemini:
        type: object
        properties:
          apiKey:
            type: string
          modelName:
            type: string
        required:
          - apiKey
          - modelName
        additionalProperties: false
      openai:
        type: object
        properties:
          apiBaseUrl:
            type: string
          apiKey:
            type: string
          modelName:
            type: string
        required:
          - apiBaseUrl
          - apiKey
          - modelName
        additionalProperties: false
    required:
      - provider
      - concurrency
      - rateLimit
      - batch
    additionalProperties: false
required:
  - randomSeed
  - source
  - inference
additionalProperties: false
$schema: http://json-schema.org/draft-07/schema#
