# yaml-language-server: $schema=./config.schema.yml

# 乱数のシード。
randomSeed: 0

source:
  # 英単語の取得方法を指定します。
  providers:
    - cmudict
    - allShortWords

  # 最大の単語数。"all"で全ての単語を取得します。
  maxNumWords: "all"

inference:
  # 読みの取得方法を指定します。
  # "gemini"、"openai"、"dummy" が選択可能です。
  provider: gemini

  # 並列実行数。レートリミットとの兼ね合いで調整してください。
  concurrency: 10

  # 1回のリクエストで取得する読みの数。
  # 二分探索で最大の数を探す場合：
  batch:
    type: bisect

    # 二分探索の上限。
    maxBatchSize: 1000

    # 余裕を持たせるための係数。
    ratio: 0.95

  # 固定値の場合：
  # batch:
  #   type: fixed
  #
  #   # 1回のリクエストで取得する読みの数。
  #   batchSize: 100

  rateLimit:
    # レートリミットに引っかかった場合のリトライ回数。
    maxRetries: 10

    # リトライ時の待ち時間。
    waitMs: 60000

    # 1回のリクエスト間の待ち時間。
    throttleMs: 1000

  # Geminiの設定。
  gemini:
    # Google AI Studioから取得したAPIキー。
    apiKey: ""

    # 使うモデルの名前。
    modelName: "gemini-2.0-flash"

  # OpenAI互換APIの設定。
  openai:
    # APIのベースURL。
    apiBaseUrl: "https://api.openai.com/v1"

    # APIキー。
    apiKey: ""

    # 使うモデルの名前。
    modelName: "text-davinci-003"
