[workspace.package]
version = "0.0.0"
edition = "2024"
description = "英単語から読みへの変換を行うライブラリ"
repository = "https://github.com/VOICEVOX/kanalizer"

[workspace]
members = ["crates/kanalizer-rs", "crates/kanalizer-py"]
resolver = "3"
