# 学習に使うデータ。
train_data: ./vendor/data.jsonl
# 評価に使うデータの割合。
eval_ratio: 0.01
# モデルの次元数。
dim: 256
# 学習するエポック数。
max_epochs: 15
# 最新のエポックから保存するモデルの数。
num_last_models_to_keep: 2
# 保存する上位のモデルの数。
num_best_models_to_keep: 2
# 乱数のシード。
seed: 0
# Optimizerの学習率
optimizer_lr: 0.001
# LayerNormを使うかどうか
use_layernorm: true
# Optimizerのweight_decay（L2正則化）
weight_decay: 0.2
