name: Test Dataset
on:
  push:
  pull_request:
    paths:
      - .github/workflows/test_dataset.yml
      - dataset/**

defaults:
  run:
    shell: bash
    working-directory: dataset

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: dataset/package.json

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: dataset/.node-version
          cache: "pnpm"
          cache-dependency-path: dataset/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Run lint
        run: pnpm run lint

      - name: Run typecheck
        run: pnpm run typecheck

      - name: Run test
        run: |
          cp ./config.test.yml ./config.yml
          pnpm run start

      - name: Check if schema is up-to-date
        run: pnpm run tools:generateConfigSchema --check
